Update python version in CONTRIBUTING.md (#1128)
The Python version 3.7 in the example results in an error.

````
$ pip install -e '.[testing]'
...
ERROR: Package 'zigpy' requires a different Python: 3.7.16 not in '>=3.8'
````

Updating to 3.8 resolves this.